# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trader.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctrader.proto\x12\x06trader\"d\n\x06\x46ilter\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.trader.InstrumentType\x12\"\n\x08\x63urrency\x18\x02 \x01(\x0e\x32\x10.trader.Currency\x12\x10\n\x08maxPrice\x18\x03 \x01(\x01\"*\n\tOfferList\x12\x1d\n\x06offers\x18\x01 \x03(\x0b\x32\r.trader.Offer\"{\n\x05Offer\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.trader.InstrumentType\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrentPrice\x18\x03 \x01(\x01\x12&\n\x0c\x62\x61seCurrency\x18\x04 \x01(\x0e\x32\x10.trader.Currency\"\x1f\n\x0cSubscription\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"%\n\x04Rate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01*A\n\x0eInstrumentType\x12\x0c\n\x08\x43URRENCY\x10\x00\x12\x12\n\x0e\x43RYPTOCURRENCY\x10\x01\x12\r\n\tCOMMODITY\x10\x02*%\n\x08\x43urrency\x12\x07\n\x03USD\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x12\x07\n\x03PLN\x10\x02\x32t\n\x06Trader\x12\x30\n\tGetOffers\x12\x0e.trader.Filter\x1a\x11.trader.OfferList\"\x00\x12\x38\n\tSubscribe\x12\x14.trader.Subscription\x1a\x11.trader.OfferList\"\x00\x30\x01\x42\x1fZ\x1d\x65xample/trading-app/v2/traderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035example/trading-app/v2/trader'
  _globals['_INSTRUMENTTYPE']._serialized_start=367
  _globals['_INSTRUMENTTYPE']._serialized_end=432
  _globals['_CURRENCY']._serialized_start=434
  _globals['_CURRENCY']._serialized_end=471
  _globals['_FILTER']._serialized_start=24
  _globals['_FILTER']._serialized_end=124
  _globals['_OFFERLIST']._serialized_start=126
  _globals['_OFFERLIST']._serialized_end=168
  _globals['_OFFER']._serialized_start=170
  _globals['_OFFER']._serialized_end=293
  _globals['_SUBSCRIPTION']._serialized_start=295
  _globals['_SUBSCRIPTION']._serialized_end=326
  _globals['_RATE']._serialized_start=328
  _globals['_RATE']._serialized_end=365
  _globals['_TRADER']._serialized_start=473
  _globals['_TRADER']._serialized_end=589
# @@protoc_insertion_point(module_scope)
